version: '3.7'

networks:
  dev_network:

volumes:
  pg_data:
  redis_data:

services:
  db:
    image: postgres:13.4
    env_file: .env
    container_name: ${POSTGRES_HOST}
    ports:
      - "5432:5432"
    networks:
      dev_network:
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis
    env_file: .env
    container_name: ${REDIS_HOST}
    ports:
      - "6379:6379"
    networks:
      dev_network:
    volumes:
      - redis_data:/data

  web:
    depends_on:
      - db
      - redis
    volumes:
      - .:/orders
    build:
      context: .
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    networks:
      dev_network:

  worker:
    build:
      context: .
    depends_on:
      - redis
    volumes:
      - .:/orders
    command: celery -A orders.celery_app worker --loglevel=INFO
    networks:
      dev_network:
