version: '3.7'

networks:
  dev_network:

services:
  db:
    image: postgres:13.4
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      dev_network:
        aliases:
          - db_main

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      dev_network:
        aliases:
          - db_redis

